<a href="https://colab.research.google.com/github/vikranthbandaru/Iris_Classification_using_NaiyeBayes/blob/main/Iris_Classification_using_NaiyeBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [ ]:
#Importing the dataset
dataset = pd.read_csv('sample_data/iris_csv.csv')


In [ ]:
#Taking a look at the dataset
dataset.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
#Splitting the dataset in independent and dependent variables
X = dataset.iloc[:,:4].values
y = dataset["class"].values

In [ ]:
# splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state = 82)



In [ ]:
#Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
X_train

array([[-1.00251953,  1.03162171, -1.40606109, -1.20517074],
       [ 2.14105929, -0.10410861,  1.62428406,  1.19627649],
       [-0.88161265,  1.03162171, -1.34888477, -1.33858448],
       [ 0.20654925, -0.10410861,  0.59511023,  0.79603529],
       [ 0.56926988, -1.23983894,  0.70946288,  0.92944902],
       [-1.24433328,  0.12303745, -1.23453212, -1.33858448],
       [-0.76070577,  0.80447565, -1.34888477, -1.33858448],
       [-0.15617138,  3.0759363 , -1.29170844, -1.07175701],
       [-0.15617138, -0.55840074,  0.42358126,  0.12896661],
       [-0.88161265,  0.80447565, -1.29170844, -1.33858448],
       [ 0.32745613, -0.10410861,  0.65228656,  0.79603529],
       [ 0.20654925, -0.78554681,  0.7666392 ,  0.52920782],
       [ 0.69017676, -0.55840074,  1.05252082,  1.32969023],
       [ 0.56926988, -0.55840074,  0.7666392 ,  0.39579408],
       [-0.88161265,  0.57732958, -1.1773558 , -0.93834327],
       [ 2.26196617,  1.71305991,  1.68146038,  1.32969023],
       [-1.12342641, -1.

In [ ]:
# Fitting Naive Bayes Classification to the Training set with linear kernel
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)
 

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

['Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor']


In [ ]:
#Lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
y_compare[:5,:]

array([['Iris-virginica', 'Iris-virginica'],
       ['Iris-virginica', 'Iris-virginica'],
       ['Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa'],
       ['Iris-setosa', 'Iris-setosa']], dtype=object)

In [ ]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[11  0  0]
 [ 0  8  1]
 [ 0  1  9]]


In [ ]:
#finding accuracy from the confusion matrix
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred += cm[row,c]
        else:
            falsePred += cm[row,c]
print('Corect predictions: ', corrPred)
print('False predictions:',falsePred)
print ('\n\Accruacy of the Naive Bayes classification is:', corrPred/(cm.sum()))                   


Corect predictions:  28
False predictions: 2

\Accruacy of the Naive Bayes classification is: 0.9333333333333333
